import { Category, Skill, Tool, Deliverable, SkillLevel, ToolType, ComplexityLevel } from './types';

export const MAIN_CATEGORIES: Partial<Category>[] = [
  {
    id: 'tech-dev',
    name: 'Technology & Development',
    description: 'Software development, web development, mobile apps, and technical solutions',
    slug: 'technology-development',
    level: 0,
    tags: ['programming', 'software', 'development', 'technical'],
  },
  {
    id: 'creative-design',
    name: 'Creative & Design',
    description: 'Graphic design, UI/UX, branding, multimedia, and creative services',
    slug: 'creative-design',
    level: 0,
    tags: ['design', 'creative', 'visual', 'branding'],
  },
  {
    id: 'business-consulting',
    name: 'Business & Consulting',
    description: 'Strategy, operations, project management, and business advisory services',
    slug: 'business-consulting',
    level: 0,
    tags: ['business', 'strategy', 'consulting', 'management'],
  },
  {
    id: 'marketing-sales',
    name: 'Marketing & Sales',
    description: 'Digital marketing, content marketing, sales, and growth strategies',
    slug: 'marketing-sales',
    level: 0,
    tags: ['marketing', 'sales', 'growth', 'digital'],
  },
  {
    id: 'writing-content',
    name: 'Writing & Content',
    description: 'Content creation, copywriting, editing, and content strategy',
    slug: 'writing-content',
    level: 0,
    tags: ['writing', 'content', 'copy', 'editorial'],
  },
  {
    id: 'operations-admin',
    name: 'Operations & Admin',
    description: 'Virtual assistance, data entry, customer support, and administrative tasks',
    slug: 'operations-admin',
    level: 0,
    tags: ['operations', 'admin', 'support', 'virtual'],
  },
  {
    id: 'engineering-architecture',
    name: 'Engineering & Architecture',
    description: 'Civil, mechanical, electrical engineering, and architectural services',
    slug: 'engineering-architecture',
    level: 0,
    tags: ['engineering', 'architecture', 'technical', 'design'],
  },
  {
    id: 'education-training',
    name: 'Education & Training',
    description: 'Course creation, tutoring, training development, and educational services',
    slug: 'education-training',
    level: 0,
    tags: ['education', 'training', 'teaching', 'learning'],
  },
  {
    id: 'legal-compliance',
    name: 'Legal & Compliance',
    description: 'Legal services, compliance, contracts, and regulatory consulting',
    slug: 'legal-compliance',
    level: 0,
    tags: ['legal', 'compliance', 'regulatory', 'contracts'],
  },
  {
    id: 'health-wellness',
    name: 'Health & Wellness',
    description: 'Healthcare consulting, wellness coaching, and health-related services',
    slug: 'health-wellness',
    level: 0,
    tags: ['health', 'wellness', 'medical', 'fitness'],
  },
];

export const TECHNOLOGY_SUBCATEGORIES: Partial<Category>[] = [
  {
    id: 'web-development',
    name: 'Web Development',
    description: 'Frontend, backend, and full-stack web development services',
    slug: 'web-development',
    parentId: 'tech-dev',
    level: 1,
    tags: ['web', 'frontend', 'backend', 'fullstack'],
  },
  {
    id: 'mobile-development',
    name: 'Mobile Development',
    description: 'iOS, Android, and cross-platform mobile application development',
    slug: 'mobile-development',
    parentId: 'tech-dev',
    level: 1,
    tags: ['mobile', 'ios', 'android', 'apps'],
  },
  {
    id: 'ai-ml',
    name: 'AI & Machine Learning',
    description: 'Artificial intelligence, machine learning, and data science solutions',
    slug: 'ai-machine-learning',
    parentId: 'tech-dev',
    level: 1,
    tags: ['ai', 'ml', 'data-science', 'automation'],
  },
  {
    id: 'devops-cloud',
    name: 'DevOps & Cloud',
    description: 'Infrastructure, cloud services, CI/CD, and system administration',
    slug: 'devops-cloud',
    parentId: 'tech-dev',
    level: 1,
    tags: ['devops', 'cloud', 'infrastructure', 'automation'],
  },
  {
    id: 'blockchain',
    name: 'Blockchain & Crypto',
    description: 'Blockchain development, smart contracts, and cryptocurrency solutions',
    slug: 'blockchain-crypto',
    parentId: 'tech-dev',
    level: 1,
    tags: ['blockchain', 'crypto', 'web3', 'defi'],
  },
];

export const COMMON_SKILLS: Partial<Skill>[] = [
  // Web Development Skills
  {
    id: 'react',
    name: 'React',
    description: 'Popular JavaScript library for building user interfaces',
    categoryId: 'web-development',
    level: SkillLevel.INTERMEDIATE,
    verificationRequired: true,
    tags: ['javascript', 'frontend', 'spa', 'component'],
    relatedSkills: ['javascript', 'typescript', 'next-js', 'redux'],
  },
  {
    id: 'node-js',
    name: 'Node.js',
    description: 'JavaScript runtime for server-side development',
    categoryId: 'web-development',
    level: SkillLevel.INTERMEDIATE,
    verificationRequired: true,
    tags: ['javascript', 'backend', 'server', 'api'],
    relatedSkills: ['javascript', 'express', 'mongodb', 'postgresql'],
  },
  {
    id: 'python',
    name: 'Python',
    description: 'Versatile programming language for web development and data science',
    categoryId: 'web-development',
    level: SkillLevel.BEGINNER,
    verificationRequired: true,
    tags: ['programming', 'backend', 'data-science', 'automation'],
    relatedSkills: ['django', 'flask', 'pandas', 'tensorflow'],
  },
  // AI/ML Skills
  {
    id: 'machine-learning',
    name: 'Machine Learning',
    description: 'Algorithms and models for data-driven predictions and automation',
    categoryId: 'ai-ml',
    level: SkillLevel.ADVANCED,
    verificationRequired: true,
    tags: ['ai', 'ml', 'data-science', 'algorithms'],
    relatedSkills: ['python', 'tensorflow', 'pytorch', 'scikit-learn'],
  },
  {
    id: 'tensorflow',
    name: 'TensorFlow',
    description: 'Open-source machine learning framework',
    categoryId: 'ai-ml',
    level: SkillLevel.ADVANCED,
    verificationRequired: true,
    tags: ['ml', 'deep-learning', 'neural-networks', 'google'],
    relatedSkills: ['python', 'keras', 'machine-learning', 'pytorch'],
  },
];

export const COMMON_TOOLS: Partial<Tool>[] = [
  {
    id: 'vscode',
    name: 'Visual Studio Code',
    description: 'Popular code editor with extensive plugin ecosystem',
    categoryId: 'tech-dev',
    type: ToolType.SOFTWARE,
    proficiencyLevels: ['Basic', 'Intermediate', 'Advanced', 'Expert'],
    relatedTools: ['git', 'docker', 'eslint'],
  },
  {
    id: 'figma',
    name: 'Figma',
    description: 'Collaborative interface design and prototyping tool',
    categoryId: 'creative-design',
    type: ToolType.PLATFORM,
    proficiencyLevels: ['Basic', 'Intermediate', 'Advanced', 'Expert'],
    relatedTools: ['sketch', 'adobe-xd', 'invision'],
  },
  {
    id: 'aws',
    name: 'Amazon Web Services',
    description: 'Comprehensive cloud computing platform',
    categoryId: 'devops-cloud',
    type: ToolType.PLATFORM,
    proficiencyLevels: ['Basic', 'Intermediate', 'Advanced', 'Expert'],
    relatedTools: ['docker', 'kubernetes', 'terraform'],
    officialCertifications: ['AWS Solutions Architect', 'AWS Developer', 'AWS SysOps'],
  },
  {
    id: 'docker',
    name: 'Docker',
    description: 'Containerization platform for application deployment',
    categoryId: 'devops-cloud',
    type: ToolType.PLATFORM,
    proficiencyLevels: ['Basic', 'Intermediate', 'Advanced', 'Expert'],
    relatedTools: ['kubernetes', 'aws', 'jenkins'],
  },
];

export const COMMON_DELIVERABLES: Partial<Deliverable>[] = [
  {
    id: 'responsive-website',
    name: 'Responsive Website',
    description: 'Mobile-friendly website that adapts to different screen sizes',
    categoryId: 'web-development',
    estimatedHours: 40,
    complexity: ComplexityLevel.MODERATE,
    requiredSkills: ['html', 'css', 'javascript', 'responsive-design'],
  },
  {
    id: 'mobile-app',
    name: 'Mobile Application',
    description: 'Native or cross-platform mobile application',
    categoryId: 'mobile-development',
    estimatedHours: 120,
    complexity: ComplexityLevel.COMPLEX,
    requiredSkills: ['mobile-development', 'ui-design', 'api-integration'],
  },
  {
    id: 'ml-model',
    name: 'Machine Learning Model',
    description: 'Trained ML model for specific business use case',
    categoryId: 'ai-ml',
    estimatedHours: 80,
    complexity: ComplexityLevel.COMPLEX,
    requiredSkills: ['machine-learning', 'python', 'data-analysis'],
  },
  {
    id: 'brand-identity',
    name: 'Brand Identity Package',
    description: 'Complete brand identity including logo, colors, and guidelines',
    categoryId: 'creative-design',
    estimatedHours: 30,
    complexity: ComplexityLevel.MODERATE,
    requiredSkills: ['graphic-design', 'branding', 'logo-design'],
  },
];